sudo: required
services: 
  - docker

before_install:
  - ls ./client
  - docker build -t dmatthe4952/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dmatthe4952/react-test npm test -- --coverage

after_success:
  - docker build -t dmatthe/multi-client ./client
  - docker build -t dmatthe/multi-nginx  ./nginx
  - docker build -t dmatthe/multi-server ./server
  - docker build -t dmatthe/multi-worker ./worker  

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - push dmatthe/multi-client
  - push dmatthe/multi-nginx
  - push dmatthe/multi-server
  - push dmatthe/multi-worker